// SPDX-License-Identifier: MIT

using System.Linq;
using Content.Client.Computer;
using Content.Client.Options.UI;
using Content.Client.UserInterface.Controls;
using Content.Goobstation.Shared.Telescience.Teleporter;
using Content.Goobstation.Shared.Telescience.Teleporter.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Goobstation.Client.Telescience.UI;

[GenerateTypedNameReferences]
public sealed partial class TeleporterConsoleWindow : FancyWindow,
    IComputerWindow<TeleporterConsoleBoundUserInterfaceState>
{
    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly IEntityManager _entManager = default!;
    private readonly SharedTeleporterSystem _teleporter;
    private readonly SharedTeleporterControllerSystem _teleporterController;

    public List<EntityUid> Beacons = new();
    public EntityUid CurrentBeacon;

    public TeleporterConsoleWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _teleporter = _entManager.System<SharedTeleporterSystem>();
        _teleporterController = _entManager.System<SharedTeleporterControllerSystem>();

        // TODO: "Gate" option
        RegimeOption.Clear();
        RegimeOption.AddItem("Teleporter", 0);

        UpdateTargets();
    }

    public void SetupComputerWindow(ComputerBoundUserInterfaceBase bui)
    {
        TargetOption.OnItemSelected += args =>
        {
            OnItemSelected(bui, args);
        };
        /*RepealAllButton.OnPressed += args =>
        {
            OnRepealAllPressed(cb, args);
        };
        AuthorizeButton.OnPressed += args =>
        {
            OnAuthorizePressed(cb, args);
        };
        RepealButton.OnPressed += args =>
        {
            OnRepealPressed(cb, args);
        };*/
    }

    /*private void OnRepealAllPressed(ComputerBoundUserInterfaceBase cb, BaseButton.ButtonEventArgs obj)
    {
        cb.SendMessage(new EmergencyShuttleRepealAllMessage());
    }

    private void OnRepealPressed(ComputerBoundUserInterfaceBase cb, BaseButton.ButtonEventArgs obj)
    {
        cb.SendMessage(new EmergencyShuttleRepealMessage());
    }

    private void OnAuthorizePressed(ComputerBoundUserInterfaceBase cb, BaseButton.ButtonEventArgs obj)
    {
        cb.SendMessage(new EmergencyShuttleAuthorizeMessage());
    }*/

    public void UpdateTargets()
    {
        List<EntityUid> sortedBeacons = [.. _teleporter.GetTeleporterBeacons().OrderBy(p => _teleporter.GetBeaconName(p))];

        Beacons = sortedBeacons;
        foreach (EntityUid beacon in sortedBeacons)
            TargetOption.AddItem(_teleporter.GetBeaconName(beacon));
    }

    private void OnItemSelected(ComputerBoundUserInterfaceBase bui, OptionButton.ItemSelectedEventArgs obj)
    {
        TargetOption.SelectId(obj.Id);
        Log.Error(obj.Id.ToString());
        CurrentBeacon = Beacons[obj.Id];
        //bui.SendMessage(new TeleporterControllerSetBeaconMessage(CurrentBeacon));
    }

    public void UpdateState(TeleporterConsoleBoundUserInterfaceState state)
    {
        
        // TODO: Loc and cvar for this.
        /*_earlyLaunchTime = scc.EarlyLaunchTime;

        AuthorizationsContainer.RemoveAllChildren();
        var remainingAuths = scc.AuthorizationsRequired - scc.Authorizations.Count;
        AuthorizationCount.Text = Loc.GetString("emergency-shuttle-ui-remaining", ("remaining", remainingAuths));

        foreach (var auth in scc.Authorizations)
        {
            AuthorizationsContainer.AddChild(new Label
            {
                Text = auth,
                FontColorOverride = Color.Lime,
            });
        }*/
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        /*if (_earlyLaunchTime == null)
        {
            Countdown.Text = "00:10";
        }
        else
        {
            var remaining = _earlyLaunchTime.Value - _timing.CurTime;

            if (remaining < TimeSpan.Zero)
                remaining = TimeSpan.Zero;

            Countdown.Text = $"{remaining.Minutes:00}:{remaining.Seconds:00}";
        }*/
    }
}